=== Rengar-Yang/Medical-Device/终端上板代码工程/UI_Engineering2/DISPLAY/Middlewares/ST/touchgfx_backup1/framework/tools/textconvert/schema/texts.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <!--Types-->
  <xs:simpleType name="direction" final="restriction" >
    <xs:restriction base="xs:string">
      <xs:enumeration value="LTR" />
      <xs:enumeration value="RTL" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="alignment" final="restriction" >
    <xs:restriction base="xs:string">
      <xs:enumeration value="Left" />
      <xs:enumeration value="LEFT" />
      <xs:enumeration value="left" />
      <xs:enumeration value="Center" />
      <xs:enumeration value="CENTER" />
      <xs:enumeration value="center" />
      <xs:enumeration value="Right" />
      <xs:enumeration value="RIGHT" />
      <xs:enumeration value="right" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="bpp" final="restriction" >
    <xs:restriction base="xs:string">
      <xs:enumeration value="1" />
      <xs:enumeration value="2" />
      <xs:enumeration value="4" />
      <xs:enumeration value="8" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="fallbackCharacter" final="restriction" >
    <xs:restriction base="xs:string">
      <xs:pattern value="|.|skip|(0x[0-9a-fA-F]{1,4})" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="ellipsisCharacter" final="restriction" >
    <xs:restriction base="xs:string">
      <xs:pattern value="|.|skip|(0x[0-9a-fA-F]{1,4})" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="wildcardCharacterRanges" final="restriction" >
    <xs:restriction base="xs:string">
      <xs:pattern value="|^(.)-(.)(.*)$|^(0[xX][0-9a-fA-F]+|\d+)(.*)|^(0[xX][0-9a-fA-F]+|\d+)-(0[xX][0-9a-fA-F]+|\d+)(.*)$" />
    </xs:restriction>
  </xs:simpleType>

  <!--TextDatabase specification-->
  <xs:element name="TextDatabase">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Texts">
          <xs:complexType>
            <xs:sequence>
              <xs:element minOccurs="0" maxOccurs="unbounded" name="Text">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element minOccurs="1" maxOccurs="unbounded" name="Translation">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute name="Language" type="xs:string" use="required" />
                            <xs:attribute name="TypographyId" type="xs:string" use="optional" />
                            <xs:attribute name="Alignment" type="alignment" use="optional" />
                            <xs:attribute name="Direction" type="direction" use="optional" />
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="Id" type="xs:string" use="required" />
                  <xs:attribute name="TypographyId" type="xs:string" use="required" />
                  <xs:attribute name="Alignment" type="alignment" use="required" />
                  <xs:attribute name="Direction" type="direction" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Typographies">
          <xs:complexType>
            <xs:sequence>
              <xs:element minOccurs="0" maxOccurs="unbounded" name="Typography">
                <xs:complexType>
                  <xs:attribute name="Id" type="xs:string" use="required" />
                  <xs:attribute name="Font" type="xs:string" use="required" />
                  <xs:attribute name="Size" type="xs:unsignedByte" use="required" />
                  <xs:attribute name="Bpp" type="bpp" use="required" />
                  <xs:attribute name="FallbackCharacter" type="fallbackCharacter" use="optional" />
                  <xs:attribute name="WildcardCharacters" type="xs:string" use="optional" />
                  <xs:attribute name="WidgetWildcardCharacters" type="xs:string" use="optional" />
                  <xs:attribute name="WildcardCharacterRanges" type="wildcardCharacterRanges" use="optional" />
                  <xs:attribute name="EllipsisCharacter" type="ellipsisCharacter" use="optional" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="Version" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Rengar-Yang/Medical-Device/终端上板代码工程/UI_Engineering2/DISPLAY/Middlewares/ST/touchgfx_backup1/framework/tools/textconvert/schema/texts.xml
<?xml version="1.0" encoding="utf-8"?>
<TextDatabase xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="texts.xsd" Version="4.18.0">
  <Texts>
    <Text Id="Main_text" TypographyId="Normal" Alignment="Left" Direction="LTR">
      <Translation Language="GB">Lorem Ipsum is simply dummy &#10;text of the printing and type-&#10;setting industry.</Translation>
      <Translation Language="AR" TypographyId="Normal_arabic" Alignment="Right" Direction="RTL">لوريم إيبسوم(Lorem Ipsum)&#10;هو ببساطة نص شكلي (بمعنى أن &#10;الغاية هي الشكل وليس المحتوى) &#10;ويُستخدم في صناعات المطابع &#10;ودور النشر.</Translation>
    </Text>
    <Text Id="Switch_language" TypographyId="Button_style_arabic" Alignment="Center" Direction="LTR">
      <Translation Language="GB">العربية</Translation>
      <Translation Language="AR" TypographyId="Button_style" Direction="RTL">English</Translation>
    </Text>
    <Text Id="Tick_counter" TypographyId="Normal" Alignment="Left" Direction="LTR">
      <Translation Language="GB">Timer: &lt;number&gt;</Translation>
      <Translation Language="AR" TypographyId="Normal_arabic" Alignment="Right" Direction="RTL">مؤقت: &lt;x&gt;</Translation>
    </Text>
  </Texts>
  <Typographies>
    <Typography Id="Normal" Font="Asap-Regular.ttf" Size="14" Bpp="4" FallbackCharacter="skip" WildcardCharacterRanges="0-9" />
    <Typography Id="Normal_arabic" Font="arabtype.ttf" Size="24" Bpp="4" FallbackCharacter="skip" WildcardCharacterRanges="0-9" />
    <Typography Id="Button_style" Font="Asap-Regular.ttf" Size="18" Bpp="4" />
    <Typography Id="Button_style_arabic" Font="arabtype.ttf" Size="26" Bpp="4" />
  </Typographies>
</TextDatabase>
